// DO NOT EDIT. This file is generated by deco.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $$$$$$$$$$$0 from "./apps/deco/blog.ts";
import * as $$$$$$$$$$$1 from "./apps/deco/htmx.ts";
import * as $$$$$$$$$$$2 from "./apps/site.ts";
import * as $$$$$$0 from "./sections/BlogPosts.tsx";
import * as $$$$$$9 from "./sections/doctor/Cards.tsx";
import * as $$$$$$10 from "./sections/doctor/ContactForm.tsx";
import * as $$$$$$11 from "./sections/doctor/Faqs.tsx";
import * as $$$$$$12 from "./sections/doctor/Footer.tsx";
import * as $$$$$$13 from "./sections/doctor/ImageWithText.tsx";
import * as $$$$$$14 from "./sections/doctor/ImageWithTextHero.tsx";
import * as $$$$$$15 from "./sections/doctor/MainHero.tsx";
import * as $$$$$$16 from "./sections/doctor/ScheduleAppointment.tsx";
import * as $$$$$$17 from "./sections/doctor/Testimonials.tsx";
import * as $$$$$$18 from "./sections/doctor/Text.tsx";
import * as $$$$$$1 from "./sections/Faq.tsx";
import * as $$$$$$2 from "./sections/Footer.tsx";
import * as $$$$$$3 from "./sections/Header.tsx";
import * as $$$$$$19 from "./sections/hero-1.tsx";
import * as $$$$$$20 from "./sections/hero-2.tsx";
import * as $$$$$$4 from "./sections/Hero.tsx";
import * as $$$$$$21 from "./sections/hero2.tsx";
import * as $$$$$$22 from "./sections/images/Banner.tsx";
import * as $$$$$$5 from "./sections/ImageWithParagraph.tsx";
import * as $$$$$$6 from "./sections/Logos.tsx";
import * as $$$$$$7 from "./sections/Testimonials.tsx";
import * as $$$$$$8 from "./sections/Theme/Theme.tsx";

const manifest = {
  "sections": {
    "site/sections/BlogPosts.tsx": $$$$$$0,
    "site/sections/doctor/Cards.tsx": $$$$$$9,
    "site/sections/doctor/ContactForm.tsx": $$$$$$10,
    "site/sections/doctor/Faqs.tsx": $$$$$$11,
    "site/sections/doctor/Footer.tsx": $$$$$$12,
    "site/sections/doctor/ImageWithText.tsx": $$$$$$13,
    "site/sections/doctor/ImageWithTextHero.tsx": $$$$$$14,
    "site/sections/doctor/MainHero.tsx": $$$$$$15,
    "site/sections/doctor/ScheduleAppointment.tsx": $$$$$$16,
    "site/sections/doctor/Testimonials.tsx": $$$$$$17,
    "site/sections/doctor/Text.tsx": $$$$$$18,
    "site/sections/Faq.tsx": $$$$$$1,
    "site/sections/Footer.tsx": $$$$$$2,
    "site/sections/Header.tsx": $$$$$$3,
    "site/sections/hero-1.tsx": $$$$$$19,
    "site/sections/hero-2.tsx": $$$$$$20,
    "site/sections/Hero.tsx": $$$$$$4,
    "site/sections/hero2.tsx": $$$$$$21,
    "site/sections/images/Banner.tsx": $$$$$$22,
    "site/sections/ImageWithParagraph.tsx": $$$$$$5,
    "site/sections/Logos.tsx": $$$$$$6,
    "site/sections/Testimonials.tsx": $$$$$$7,
    "site/sections/Theme/Theme.tsx": $$$$$$8,
  },
  "apps": {
    "site/apps/deco/blog.ts": $$$$$$$$$$$0,
    "site/apps/deco/htmx.ts": $$$$$$$$$$$1,
    "site/apps/site.ts": $$$$$$$$$$$2,
  },
  "name": "site",
  "baseUrl": import.meta.url,
};

export type Manifest = typeof manifest;

export default manifest;
